title: Explication des variables de la palette de couleurs
hero_image: images/banner.png
description: Explication des variables de la palette de couleurs.
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - 
    title: Explication des variables de la palette de couleurs
